Optimize Workflows for Github Actions (#5)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,6 +20,7 @@ jobs:
 
       - name: Build ISO in Arch Container
         run: |
+          set -e
           docker exec arch-container bash -c "
           pacman -Syu --noconfirm &&
           pacman -S --noconfirm git archiso grub &&
@@ -29,21 +30,19 @@ jobs:
 
       - name: Rename ISO to Arch.iso
         run: |
+          set -e
           docker exec arch-container bash -c "
-          # Find the created ISO (assuming only one .iso file in the output directory)
-          iso_file=\$(ls /workdir/out/*.iso | head -n 1) &&
-          mv \$iso_file /workdir/out/Arch.iso
+          iso_file=\$(ls /workdir/out/*.iso 2>/dev/null | head -n 1) &&
+          [ -n \"\$iso_file\" ] && mv \$iso_file /workdir/out/Arch.iso || echo 'No ISO file found.'
           "
 
       - name: List ISO files
         run: |
-          # List files in the output directory to verify renaming
-          docker exec arch-container bash -c "ls -l /workdir/out/"
+          docker exec arch-container bash -c "ls -l /workdir/out/ || echo 'Failed to list files.'"
 
       - name: Copy ISO to Host
         run: |
-          # Copy the renamed ISO to the host
-          docker cp arch-container:/workdir/out/Arch.iso ${{ github.workspace }}/
+          docker cp arch-container:/workdir/out/Arch.iso ${{ github.workspace }}/ || echo 'Failed to copy ISO to host.'
 
       - name: Get current date
         id: date
@@ -76,5 +75,5 @@ jobs:
 
       - name: Clean Up
         run: |
-          docker stop arch-container
-          docker rm arch-container
+          docker stop arch-container || echo 'Failed to stop the container.'
+          docker rm arch-container || echo 'Failed to remove the container.'
diff --git a/.github/workflows/dockerfile-check.yml b/.github/workflows/dockerfile-check.yml
--- a/.github/workflows/dockerfile-check.yml
+++ b/.github/workflows/dockerfile-check.yml
@@ -18,10 +18,8 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Build Docker container
+      - name: Build and Run Docker container
         run: |
-         docker build -t arch-iso-builder .
-
-      - name: Make ISO in Docker container
-        run: |
-         docker run --rm --privileged -v $(pwd):/workdir arch-iso-builder bash -c "mkarchiso -v -w workdir/ -o out/ ."
+          set -e  # Exit immediately if a command exits with a non-zero status
+          docker build -t arch-iso-builder . || { echo "Docker build failed"; exit 1; }
+          docker run --rm --privileged -v "$(pwd)":/workdir arch-iso-builder bash -c "mkarchiso -v -w workdir/ -o out/ ." || { echo "ISO creation failed"; exit 1; }
